scssphp/scssphp

src/Parser.php, tests/inputs/scss_css.scss, tests/outputs/scss_css.css, tests/outputs_numbered/scss_css.css
Enable eatWhitespaces in matchChar() and update unit tests.
Closes #21
=> Fix #21 : Support whitespaces inside :not()

src/Compiler.php, tests/inputs/builtins.scss, tests/outputs/builtins.css, tests/outputs_numbered/builtins.css
Fixes #32
Compiles latest version of Bootstrap: https://github.com/twbs/bootstrap/commit/b02bae769e989838229c13a7c97d5af4c338601d
=> Fix zip function to allow all types as arguments #32

.travis.yml
nightly on Travis installs PHP 8.0-dev, but there is no PHPUnit version supporting it yet.
=> Remove the PHP nightly job on Travis

src/Formatter.php
There is an (accumulating) column error in case `$str` is modified after the `sourceMapGenerator->addMapping` arguments are set. I rearranged the code to fix the error.
=> Fixed sourceMapGenerator bug if semicolons are stripped.

src/Compiler.php
This makes the call stack much more helpful, as it gives us the chain of imports leading to the error, not only the chain of function calls. This matches the behavior of dart-sass and libsass regarding error reporting.
=> Add named call stack entries for imports

src/Compiler.php
When using a return directive, a frame was leaked in the call stack.
This has 2 effects:
- the call stack displayed in error message becomes very confusing, as it includes unrelated locations
- the call stack grows much more than necessary. This has a cost when computing the call stack message, and makes it more likely to reach the threshold used to prevent infinite loops (without actually doing infinite loops).
Another frame leak happened when using a return directive in a forbidden location (so now leaking 2 frames due to the previous leak), in case exceptions are ignored (to allow the code to continue to execute and so to care about it).
This will probably solve #89 but I haven't checked.
=> Fix leaks in the call stack

src/Cache.php, src/Colors.php, src/Compiler.php, src/Formatter.php, src/Formatter/Nested.php, src/Node/Number.php, src/Parser.php, src/SourceMap/SourceMapGenerator.php
Some built-in functions can be turned into specific opcodes at compile time when the compiler is sure that they will be used (i.e. no namespace fallback is needed). This can have a major performance impact when they appear in hot paths.
In the profiling, is_null was one of the most expansive function due to the huge number of times it was used. And it is one of the functions which is optimized. Closes #96.
This change has been done using the php-cs-fixer tool, which maintains a list of functions which benefit from such optimization.
=> Qualify function calls when the compiler can optimize them

bin/pscss, src/Compiler.php, src/Node/Number.php, tests/SassSpecTest.php
A precision of 10 is enough for all browsers to avoid rounding issues.
This matches the behavior of dart-sass in which it cannot be configured either.
I used the Symfony convention (also used by the Drupal for instance, and maybe others) to report the deprecation of the setter with `@trigger_error('...', E_USER_DEPRECATED);` to make it discoverable in projects using a compatible deprecation collector. I can remove it if your prefer.
Closes #141
=> Drop support for configuring the precision

tests/SassSpecTest.php
Trying to close the error stream twice does not work. It is closed after the `try/catch`
=> Fix the build mode for error tests

tests/SassSpecTest.php
The new version of the code makes sure that 256M is the minimum limit, but will preserve any higher limit.
This makes it possible to use PCOV to collect code coverage while running tests, as it requires lots of memory.
=> Fix the logic setting the memory_limit in SassSpecTest

src/Parser.php
The parse() method extract line numbers when setting the buffer, but other parse methods don't do it, while they might still trigger errors relying on that data.
This fixes tests broken by 8a30458de984e1fa79181c72378b5743907867e7 when it added parser errors in those other entrypoints.
Note that line numbers will be off for such errors. What dart-sass does is that it catches exceptions and re-throw them with an updated location when it uses the selector parser during the scss compilation. But we cannot do that easily in the current codebase. So at least, this ensures that the proper error message gets reported (even with a broken line number) instead of reporting a bug in the parser.
=> Fix the initialization of the parser for secondary entrypoints

src/Util.php
`mb_chr(0)` is broken, returning an empty string instead of a string containing the NUL byte.
Refs #189
=> Fix compat with PHP 7.2 with mbstring loaded

src/Compiler.php
`feature-exists` is meant to provide metadata about features which are supported by the Sass implementation. It does not make sense to let users customize that as they cannot actually implement the features at the same time.
Such list is not customizable either in official Sass implementations
=> Deprecate registering additional features

composer.json
- don't override the minimum stable but use Composer's default one (`stable`)
- sort packages in requirements (this helps when using `composer require` to add new ones)
- remove the outdated `composer archive` config in favor of `.gitattributes` (which Composer will use as fallback) to avoid maintaining the list twice (thus, this config is relevant only when adding the package in a Satis repo, as packagist.org does not build archives but relies on the GitHub ones)
=> Clean the composer.json

src/Compiler.php, tests/specs/sass-spec-exclude.txt
The unit table in `Number` includes the units from CSS Units Level 3
=> Mark the units-level-3 feature as implemented

src/Node/Number.php, tests/specs/sass-spec-exclude.txt
The Sass modulo works for floats and the returned value must have the same sign than the right operand (i.e. the Ruby behavior for modulo).
In PHP, `%` is the integer modulo. `fmod` must be used for float modulo.
And the PHP behavior is to is to use the sign of the left operand rather than of the right one.
=> Fix the implementation of modulo

src/Compiler.php, tests/inputs/operators.scss, tests/outputs/operators.css
Converting the number to a color and calling `opColorColor` is not OK for `==` and `!=` operators. Even when supporting color arithmetic, a number was never equal to a color.
=> Fix the implementation of == and != between number and colors

src/Compiler.php, tests/specs/sass-spec-exclude.txt
These Sass functions are meant to change case of ASCII chars only.
=> Fix the behavior of to-uppercase and to-lowercase

src/Parser.php, tests/outputs/scss_css.css, tests/specs/sass-spec-exclude.txt
Unicode escape sequence can end with a space to delimit them from the next char. This space is always allowed, and is necessary when the sequence is shorter than 6 chars and the next char would be is part of the hex alphabet (as it would be valid as part of the sequence). See https://drafts.csswg.org/css-syntax/#consume-escaped-code-point
This fixes will allow #226 to also validate the `core_functions/string/index/combining_character` spec (which uses such an escape sequence).
=> Fix the matching of the space ending an escape sequence

src/Compiler.php
The call function does not have any special evaluation behavior for its arguments, even when calling the special if() function.
Fixes #216 
Specs for that issue have been submitted upstream at https://github.com/sass/sass-spec/pull/1588. I confirmed locally that these specs are indeed failing without this patch and passing with it.
=> Fix spec compliance for the call function

src/Compiler.php, src/Util.php, tests/specs/sass-spec-exclude.txt
It must count unicode codepoints, not bytes. The implementation is now compliant with mbstring or with iconv.
=> Fix the behavior of str-index

src/Block.php, src/Compiler.php, src/Formatter/Compressed.php, src/Formatter/Crunched.php, src/Formatter/Debug.php, src/Formatter/Expanded.php, src/Formatter/Nested.php, src/Formatter/OutputBlock.php, src/Node/Number.php, src/Parser.php, src/SourceMap/Base64VLQ.php, src/Util.php
As we decided to keep support for PHP 5.6 in #202, I started looking into adding static analysis tooling on the project, so that we benefit from type checks as much as possible even when the runtime won't have them.
I have a branch locally in which I start to setup phpstan, using its baseline feature to ignore all errors happening in our legacy code. this work is not ready to be merged yet, because we are affected by [a bug related to classes named `Number`](https://github.com/phpstan/phpstan/issues/4039). Due to that bug, I initially based that branch on top of #205. But as I'm now focusing on some improvements for 1.4, I decided to base that work again on master directly and I patched the phpstan bug instead. Once the bugfix is merged and released, I will submit a PR with the setup.
In …
=> Improve phpdoc

src/Compiler.php, src/Formatter.php, src/SourceMap/SourceMapGenerator.php
=> Fix sourcemaps

bin/pscss
Instead of relying on PHP's rendering of an uncaught exception, the SassException is caught and its message is displayed. This avoids showing the PHP stack trace which is not relevant for fixing an issue in the sass file.
Before:
```
PHP Fatal error:  Uncaught ScssPhp\ScssPhp\Exception\CompilerException: $number: Expected 25px to have no units: imports/simple.scss on line 4, at column 5
Call Stack:
#0 import imports/simple.scss import.scss on line 10 in /home/stof/src/scssphp/scssphp/src/Compiler.php:5413
Stack trace:
#0 /home/stof/src/scssphp/scssphp/src/Compiler.php(413): ScssPhp\ScssPhp\Compiler->error()
#1 /home/stof/src/scssphp/scssphp/bin/pscss(196): ScssPhp\ScssPhp\Compiler->compile()
#2 {main}
thrown in /home/stof/src/scssphp/scssphp/src/Compiler.php on line 5413
```
After:
``` …
```
=> Add a better error rendering of sass errors in pscss

src/Compiler.php
the result seemed to be dependant from the environment, make it more robust
This is a fix for #246
=> Fix test suite on strtolower/strtoupper on non ascii-chars 

src/Parser.php, tests/inputs/selectors.scss, tests/outputs/selectors.css
=> Fix #245 : discard comments at the start of re-parsed selectors

Makefile
Refs #246 
Running `make test` or `make sass-spec` will not automatically run `composer update` if the composer.json was modified since the last time the vendor folder was updated. This avoids forgetting it when a PR is merged to upgrade sass-spec for instance.
For contributors not using `make`, this won't help of course. They will still need to remember running `composer update`, just like the current status quo.
=> Improve the Makefile to ensure vendors are uptodate

src/Exception/SassScriptException.php
When I introduced `SassScriptException` in #188, I tagged it as `@internal`. But that was a mistake. For developers *using* the library, this exception is indeed an internal implementation detail that they will never see. But for developers *extending* SassScript with custom functions, this exception is absolutely not an internal implementation detail. It should actually be the go-to exception for custom function rather than relying on `Compiler::error()`. It avoids needing access to the Compiler to trigger errors (which is why `Number` uses it, and why `SassScriptException` exists in `dart-sass` too, where I got the idea).
=> Expose SassScriptException as a non internal class

src/Exception/SassScriptException.php, src/Node/Number.php
This ensures consistent formatting of the error with argument name.
For now, this is used only once, but this is because our functions are not using `SassScriptException` yet. But looking in dart-sass, this pattern of using an argument name for the error reporting is very common.
Adding the factory method now rather than when refactoring values allows custom functions to start using it if they want (see #239 making this non-internal).
=> Add a factory method for SassScriptException with an argument name

composer.json, src/Compiler.php
When using an API for which we trigger a deprecation warning, the testsuite will now report a failure, unless the test triggering it is in the `legacy` group (we don't have any right now, as we don't have BC tests ensuring the deprecated APIs keep working the same). This ensures that the core does not trigger its own deprecations.
Here is how the output looks like (that's what I got when running tests locally before fixing the `Compiler.php` code):
=> Forbid using our own deprecated APIs outside legacy tests

src/Compiler.php
Following https://github.com/scssphp/scssphp/commit/de45205 test suite was broken in my environment:
```
There were 12 failures:
1) ScssPhp\ScssPhp\Tests\SassSpecTest::testTests with data set "4051/5713. libsass-closed-issues/issue_1243/debug" ('4051/5713. libsass-closed-iss.../debug', array('', '@debug("foo")\n\n', array(), ''), array('', 'input.scss:1 DEBUG: foo\n', '', array()))
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'input.scss:1 DEBUG: foo'
+'/var/folders/wh/ypj7kkt52dxf98t071c53lhm0000gn/T/sass-spec/libsass-closed-issues/issue_1243/debug/input.scss:1 DEBUG: foo'
/Users/cedric/Sites/libs/scssphp/tests/SassSpecTest.php:360
...
```
This is because the tmp folder  `/var/folders/wh/ypj7kkt52dxf98t071c53lhm0000gn/..` becomes …
=> apply realpath() to the input path to use the same in the parser also

src/Compiler.php, src/Parser.php, tests/inputs/selectors.scss, tests/outputs/selectors.css, tests/specs/sass-spec-exclude.txt
Escaped chars in selectors should not been systematically unescaped in the output, leading to unvalid selectors that the parser itself is refusing as valid. 
For now we are keeping the escaped sequence in the selector, in a normalize way, to not take the risk to produce an unvalid selector 
The target and safer should be to have the same way of managing escaping as in string and keyword: store the real char in a non escaped form in the selector representation, and escape in the output what should be escaped only.
But this require a better structure for representation of selectors out of the parser, otherwise this would more or less implie to reparse in the compiler to know what to escape, which would be a shame
(ie for instance escape non alpha first chars of identifiers and non allowed …
=> Fix #273 and escaped selector sass-spec test

src/Formatter.php
When writing new output to the same line that the previous output, the current column needs to be incremented rather than reset.
For the expanded output, the code was fine as the current column is almost always 0 at that point (due to the resetting happening when writing a new line). But the compressed output is writing everything as a single line.
Closes #275
=> Fix sourcemaps for the compressed output

src/Compiler.php
When a path is not provided in compile(), scssphp 1.4.0 uses the current working directory as the directory of the file, in an effort to keep BC with the old behavior.
But this actually break things for projects which were removing that import path. And when combining that with open_basedir restrictions, it can create issues.
Closes #271
=> Fix BC with projects disabling the CWD-based import resolution

scss.inc.php, src/Compiler.php, src/Util/Path.php, tests/ApiTest.php, tests/Util/PathTest.php
The new logic for imports was ported from the dart-sass code, but missed the behavior of path.join in dart when an absolute path is provided. This logic has now been ported as well.
=> Fix support for absolute paths in import rules

bin/pscss
- add support for writing the output to a file rather than stdout. Closes #267
- add support for choosing between a source map file or an inline source map when writing to a file (defaults to a map file for consistency with the official sass CLI)
- add support for embedding sources in source maps
=> Improve the pscss CLI

scss.inc.php, src/Compiler.php, src/Compiler/CompilationResult.php, src/SourceMap/SourceMapGenerator.php
This is an implementation of #222 and fixing #268 in a efficient way
As a matter of fact, there is no BC break.
The CompilationResult is storing 3 differents lists:
- parsedFiles, as it was in the Compiler Class, listing the parsed files with their timestamp
- importedFiles which list all the findImport resolved as a file, with the current dir and search path. This is used for a deep check of cache validity
- includedFiles which list all the `@import` path, whether it's resolved as a file (then it is in the importedFiles as well) or a just kept as a css `@import` directive. We are not using this list, but this is an output of dart-sass and while refactoring I tried to stay as close as possible.
I think that importedFiles and parsedFiles could probably be merged, but I didn't had a deep …
=> Refactor compilation result

composer.json, tests/SassSpecTest.php, tests/specs/sass-spec-exclude.txt
New skipped specs (either due to infinite loops or to not implementing the right behavior) should be fixed when working on #194
=> Upgrade sass-spec for the testsuite

scss.inc.php, src/Compiler.php, src/Logger/LoggerInterface.php, src/Logger/QuietLogger.php, src/Logger/StreamLogger.php, tests/ExceptionTest.php, tests/InputTest.php, tests/SassSpecTest.php
The object-oriented interface makes it simpler to customize the reporting of warnings (no need to use a special stream wrapper to keep it realtime). It will also simplify future internal refactorings as object references are easier to share than PHP resources.
As a nice benefit, the stderr stream opened automatically by the compiler is now properly closed when it is not used anymore.
Closes #223
=> Introduce a LoggerInterface

composer.json, src/Util.php
Sass strings are indexed in term of Unicode codepoints. Falling back to byte-based indexes when neither mbstring nor iconv are available on the system is not spec-compliant as it changes how string indexes are working. iconv is enabled by default in PHP (this might not be true on all distributions though as they customize how they build PHP) and mbstring is quite common, especially now that UTF-8 is the norm.
Installing mbstring is recommended as it has better performance than iconv. Scssphp is only using iconv as fallback when mbstring is not available.
closes #203
=> Require either mbstring or iconv

src/Compiler.php
This cleans things for the helper added in https://github.com/scssphp/scssphp/pull/264:
- fix the phpdoc
- make the helper private as it is an internal one. that avoids having to preserve BC for it
- remove an unused broken unit coercion (keeping a broken coercion in the code would create bugs if we start using it later)
=> Clean assertions in color functions

src/Compiler.php
assertNumber returns the asserted value but restricts the type, which tells the type checker about the assertion as well.
=> Improve type checks in the assertion helper

phpstan-baseline.neon, src/CompilationResult.php, src/Compiler.php
This class is part of the main API of the library. It is not an internal implementation detail of the compiler.
The renaming is not a BC break, as the class is not part of a release yet.
=> Move CompilationResult to the root of the package

phpstan-baseline.neon, src/CompilationResult.php, src/Compiler.php, src/Compiler/CachedResult.php
This reworks the CompilationResult result object introduced in #270. This has to be merged before the next release (otherwise CompilationResult will be covered by BC and prevent the changes)
- `Scssphp\Scssphp\CompilationResult` is now an immutable value object instead of a mutable one
- `Scssphp\Scssphp\CompilationResult` now longer exposes some internal API publicly
- metadata used only by the caching layer are not exposed in the CompilationResult anymore. They are kept internal (the object stored in the cache is an internal `CachedResult` object wrapping the CompilationResult)
- metadata collected during the compilation are stored in properties of the Compiler (that are reset at the end of the compilation to free memory, except for `parsedFiles` which has a deprecated getter)
- the …
=> Rework CompilationResult

src/Compiler.php, src/Node/Number.php, tests/SassSpecTest.php, tests/specs/sass-spec-exclude.txt
- compatible units must be supported rather than only same unit
- bounds of the loop must be integers (the previous implementation was expecting that without validating it, which was creating infinite loops when trying to execute).
Closes #194
=> Fix the handling of for loops

phpunit.xml.dist, src/Compiler.php, tests/ApiTest.php
Such cases now trigger a deprecation warning hinting towards using `registerFunction` instead (when it is a new function and not an override of a core one).
=> Deprecate registering custom function through inheritance

src/Parser.php
The Parser does not use mbstring itself. The only reason to change the encoding is to ensure compatibility with the mbstring.func_overload feature of PHP, as we rely on the fact that standard PHP functions are dealing with bytes, not with multibyte chars (which would not be compatible with preg_match offsets which are not overloaded).
There is no need to change that global state if that obsolete PHP feature is not enabled.
=> Avoid changing the mbstring encoding when useless in the Parser

src/Compiler.php, tests/specs/sass-spec-exclude.txt
This allows having proper error reporting when using it with arguments while it expects none.
=> Define the signature for the unique-id function

src/Compiler.php, tests/inputs/list.scss, tests/specs/sass-spec-exclude.txt
The implementation was done based on a variadic argument, because of a mistake in the way to write one of our own tests.
=> Fix the implementation of list-separator

tests/compare-scss.sh
I discovered that the `tests` folder contained an outdated script comparing the output for our own functional tests (the ones in `tests/inputs/` with expectations in `tests/output/`, used by InputTest) to the output of ruby-sass's `scss` executable.
This script is now updated to use the dart-sass CLI instead. I also improved the way invalid scss files (i.e. the ones for which dart-sass fails) are reported.
=> Improve comparison script

src/Compiler.php, tests/ApiTest.php
This behavior is not compliant with official Sass implementations. Such imports must always be emitted as CSS imports.
=> Deprecate returning an imported file for static imports

src/Compiler.php, tests/ApiTest.php
Replacing a core function will lead to surprising results for authors as the function will probably not match the behavior of the core function (otherwise, there would be no point deprecating it).
Refs #209
=> Deprecate overriding core functions through registerFunction

phpstan-baseline.neon, src/Compiler.php
This avoids exposing them as a public API that needs to be covered with backward compatibility.
=> Change the visibility of new color helpers to private

src/Compiler.php
This makes it a lot easier to debug issues as it allows to access the original stack trace if the exception was unexpected.
=> Keep the original SassScriptException as previous exception

src/Compiler.php
The Sass language parsing is specified in term of Unicode (as is CSS).
The implementation of encoding in the compiler is not about converting from the provided encoding to unicode before parsing, but about replacing the parser with a non-compliant one which is not based on Unicode.
Closes #322
=> Deprecate the Compiler::setEncoding method

src/Parser.php, tests/inputs/scss_css.scss
This is not a valid Sass syntax (and has never been one).
This is something that was implemented in leafo/scssphp in the commit https://github.com/scssphp/scssphp/commit/16251d9790e57853017464bd9009f685505f50c8 which is described as `match some random stuff`.
Matching some random stuff is not how we comply to the spec.
=> Remove support for ignoring HTML comment delimiters during parsing

bin/pscss
This make the CLI compatible with the expectation of the official sass-spec runner.
=> Prefix errors when displaying them in the CLI

tests/inputs/map.scss, tests/inputs/nesting.scss, tests/inputs/operators.scss, tests/inputs/scss_css.scss, tests/inputs/selector_functions.scss, tests/inputs/selectors.scss, tests/inputs/variables.scss, tests/outputs/nesting.css, tests/outputs/operators.css, tests/outputs/scss_css.css, tests/outputs/selector_functions.css, tests/outputs/selectors.css, tests/outputs/variables.css
Our parser and compiler accept invalid input as long as it looks a bit like Sass. But we should not have such broken cases enforced by the testsuite.
=> Remove invalid syntax from some test fixtures

src/Compiler.php
The method is expected to display some warnings, so we should not use it as an internal helper at the same time, to unlock adding it.
=> Avoid using the libUnquote method when dealing with selector args

src/Compiler.php
Interpolations are not values. In an expression context, they must be evaluated by serializing the value in unquoted mode (where strings are never quoted).
This removes the need for a hack in the function calling layer which was making a test pass.
Now, *all* functions are receiving proper values for their arguments.
Note that this is not enough to make interpolations spec compliant (which require refactoring huge parts of the parsing and compilation), which is something that cannot be done yet.
=> Fix the handling of interpolation in expression

phpstan-baseline.neon, src/Compiler.php, src/Node/Number.php, tests/specs/sass-spec-exclude.txt
scale-color, adjust-color and change-color are expected to accept channels only through named arguments, not through positional ones.
=> Refactor the implementation of color changing functions

src/Compiler.php
This function is not standard in Sass. It is totally untested. And it has a confusing behavior: the argument must either be a glob based on an absolute path (not easy to do in a Sass file if it must be portable) or relative to the current working directory of the PHP process, not to the Sass file using the function, (which is not in the control of the author of the Sass file).
Closes #219
=> Deprecate the scssphp-glob function

bin/pscss, phpstan-baseline.neon, src/CompilationResult.php, src/Compiler.php, tests/ApiTest.php, tests/ExceptionTest.php, tests/FrameworkTest.php, tests/InputTest.php, tests/SassSpecTest.php
This restores backward compatibility on the `compile()` method by keeping a string return value.
The modern API using a CompilationResult object is now available through `compileString` instead. This modern API does not write the sourcemap to the filesystem when configuring an external sourcemap. This is expected to be done by the caller (similar to the fact the CSS is not written to disk). However, the sourcemap comment is present in the CSS.
Closes #320
=> Deprecate Compiler::compile in favor of Compiler::compileString

phpstan-baseline.neon, src/Compiler.php, tests/ExceptionTest.php, tests/specs/sass-spec-exclude.txt
Arguments are now evaluated first, resolving any splat operator. They are split between keyword arguments and positional ones, normalizing the keyword names. These values are then spread into the arguments as a second step. This allows a better validation (especially when splat is involved), which resolves some spec compliance issue. It also makes the code easier to maintain by avoiding to deal with splat operators for the argument invocation and rest arguments for the argument declaration in the same loop (the remaining ugliness is related to the data model for expressions used for the arguments, as the representation in the AST and the values API is out of scope of this refactoring).
For calls to built-in functions, the management of overloads is also refactored. Instead of trying to …
=> Refactor the processing of arguments

tests/InputTest.php
I missed it in #334 because this runs only when rebuilding the outputs, not when running tests (so not reported during a normal test run) and the missing phpdoc on the property means that PHPStorm was not finding it as a usage of the method.
=> Remove remaining usage of the deprecated compile API in tests

tests/inputs/if.scss, tests/outputs/if.css
This test was actually enforcing a non-compliant scoping rule (and the comment acknowledges that). This does not make sense to keep that in our testsuite.
=> Remove invalid test from the fixtures

src/Compiler.php, src/Warn.php
The goal of this API is to allow implementing custom functions without the need for a reference to the Compiler object. This is the next step after #239 which allowed avoid the Compiler instance to report errors.
This API is a public API for projects registering custom functions. However, it is also used internally (it is necessary to unlock #266).
For now, the warning message is logged as is. A future improvement once #303 is solved will be to inject the trace automatically for all warnings, as done in dart-sass. I even already implemented it without including it in this PR due to sass-spec failures (where we would no longer match the libsass warnings due to adding a trace but not matching the dart-sass ones due to having a different trace format), which is the reason why I opened #303. …
=> Add a high-level API to report warning

src/Compiler.php, tests/SassSpecTest.php, tests/specs/sass-spec-exclude.txt
This ensures that imports expected to resolve to a .sass file are resolved properly (and then fail due to the syntax being unsupported) rather than potentially resolving to a totally different .scss file compared to official implementations.
Closes #347
=> Take sass files into account when resolving imports

src/Compiler.php, tests/ExceptionTest.php, tests/specs/sass-spec-exclude.txt
None of the official Sass implementations are allowing to use the parent selector or complex selectors in `@extend`.
Scssphp currently generates garbage for such usage. This makes it report a proper error instead.
=> Forbid unsupported selectors in the extend directive

src/Compiler.php, src/ValueConverter.php, tests/ApiTest.php
The new API has 2 methods. One adding new variables (like the old setVariables but with a name reflecting its behavior) and one replacing all variables.
Values are expected to be converted to sass values using the new ValueConverter API before being passed to the Compiler registration methods (passing non-converted values triggers a deprecation warning). This prepares for the refactoring of the representation of values scheduled for a 2.x release, in which the ValueConverter will return values using the new API. Because of that, the type returned by the ValueConverter should be treated as opaque.
Closes #309
=> Overhaul the variable registration API

tests/inputs/builtins.scss, tests/inputs/extends.scss, tests/inputs/media.scss, tests/outputs/builtins.css, tests/outputs/extends.css, tests/outputs/media.css
This is continuing my work to ensure that our own test fixtures are not enforcing invalid scss.
After this PR, we are left with only 3 files triggering errors in dart-sass:
- `comments.scss` because it covers our non-standard support for broken interpolation in comments. This one also fails in libsass. I'd like to find a way to deprecate that behavior, but I need to spend more time on this to understand the logic.
- `operators.scss` because it uses color math. This one does not trigger errors in libsass (we might want to split it in 2)
- `extending_compound_selector.scss` because extending compound selectors is deprecated in libsass and unsupported in dart-sass. That's already a dedicated fixture file.
=> Remove invalid tests

src/Compiler.php, tests/specs/sass-spec-exclude.txt
The arguments need to be treated as codepoints, not as bytes, when computing the index.
This also implements the proper error handling for arguments.
=> Fix the implementation of str-slice

src/Compiler.php, tests/specs/sass-spec-exclude.txt
A call without arguments must not be treated like a CSS function call.
=> Fix the handling of min and max without arguments

src/Compiler.php, src/Parser.php
Closes #358
I also submitted https://github.com/sass/sass-spec/pull/1644 to cover that case in sass-spec (which we will need to skip until the 2.0.0 release as sass-spec expects an error, not a deprecation warning while ignoring the error).
=> Deprecate silent interpolation errors in multiline comments

tests/specs/sass-spec-exclude.txt
#362 actually fixed one more failing spec, but not in the initial version where I rebuilt the specs. It was only unlocked later on.
=> Rebuild the list of excluded specs

src/Compiler.php
Instead of trying to evaluate arguments on its own, it now calls the function with a rest argument instead, which is resolved by the normal handling of arguments. this allows to simplify the logic and avoid relying on the internal representation of sass argument lists there.
This is consistent with the way dart-sass implements it.
This is equivalent to this userland implementation, except of course that function names cannot be dynamic (it makes them CSS function calls) which is precisely why `call()` exists in core:
```scss
@function call($function, $args...) {
// Validate the type of function
@return #{$function}($args...);
}
```
This refactoring helps with my upcoming refactoring of the way argument lists are handled.
=> Refactor the implementation of the call function

phpstan-baseline.neon, src/Compiler.php, tests/specs/sass-spec-exclude.txt
Argument lists are expected to be a list containing positional arguments, with a way to access named arguments. The representation of the value was mixing the named arguments with the positional ones in the list, which was breaking the usage as a list (not covered by sass-spec) and also returning wrong data in the `keywords` function.
This is fixing bugs for the usage of an argument list in Sass code.
This is technically a BC break for custom host function that expect to accept arbitrary named arguments while declaring arguments explicitly. However, this is considered OK. This representation of argument lists is not documented anywhere. And in previous releases of scssphp, there was no such usages in the core either to allow discovering how to do it (change-color, scale-color and …
=> Refactor the implementation of sass argument lists

phpstan-baseline.neon, src/Compiler.php
This is necessary to allow implementing custom functions dealing with sass strings as argument through an external callback rather than extending the Compiler class.
This does not directly expose `compileStringContent` for 2 reasons:
- the name is a lot less clear about the intent
- it would expose the second argument, which is internal
=> Add a public helper to get the text of a Sass string

phpstan-baseline.neon, src/Compiler.php, tests/ApiTest.php, tests/CompilerTest.php
This deprecates registering custom functions through `registerFunction` without providing the argument declaration (formerly called `prototype` but I renamed the argument to help understanding it).
This also adds a test ensuring that all core functions are declaring their arguments (and it fixes the few missing ones found by that test).
There is still another way to register functions: extending the compiler and using our `lib*` naming convention. This one does not check for missing argument declarations, but it is already deprecated anyway.
Closes #368
=> Enforce defining arguments for all functions

phpstan-baseline.neon, src/Compiler.php, tests/ApiTest.php
This enforces that functions return a proper sass value instead.
Returning null is still allowed as this is used as a special case to render a css function instead. This case will stay supported until the refactoring of values and function signatures.
This avoids using the guessing-based value coercion for returned values. Functions must manage themselves what they return (custom functions might decide to use the ValueConverter from #355 but core functions always implement the logic directly as they know what they want to return).
=> Deprecate returning a PHP value from function implementations

src/Compiler.php
This avoids duplicating the logic when implementing custom functions.
=> Expose isTruthy as a public compiler helper

src/Compiler.php, tests/ExceptionTest.php
While working on documenting the way to work with values in custom functions, I figured out that our `assert*` helpers were not consistent in their handling of the argument name. This cleans it.
It also uses `SassScriptException` in all assertion helpers instead of throwing the CompilerException directly, which helps when documenting the fact that custom functions should use `SassScriptException` to report scripting errors (the assertion helpers in the `Number` class were already using it).
=> Improve assertion helpers

phpstan-baseline.neon, src/Compiler.php, vendor-bin/phpstan/composer.json
Some error messages have changed in the latest version of phpstan, which requires regenerating the baseline.
This also improve the types for `alterColor` to specify types for the callback arguments, to avoid an error `Comparison operation "<" between (array|float|int) and 0 results in an error.` due to the new version of phpstan inferring `$new + $base` as `float|int|array` when it does not know the type of the variables. Removing `call_user_func` to call the callbacks helps the type checks as `call_user_func` is not typed in a generic way to handle arguments properly (which I don't think is possible with phpstan generics anyway as I don't think they are as expressive as the typescript ones yet)
=> Upgrade phpstan

.github/workflows/ci.yml
The github actions environment comes with PHP 8.0 preinstalled on windows and macOS (on Linux, it has both 7.4 and 8.0), which makes the setup faster than having to install another version.
=> Use PHP 8.0 for the windows and macOS CI jobs

src/Compiler.php
We deprecated the possibility for custom importers to process CSS imports. However, when writing the documentation about it, I figured out that we were not exposing a way for importers to detect CSS imports to skip them early and always return `null` for them.
This introduces this helper, avoiding the need to copy our regex.
=> Add a helper method to allow custom importers to skip CSS imports

docs/Gemfile, docs/_config.yml, docs/_sass/_leafo.scss, docs/community/index.md, docs/docs/changelog.md, docs/docs/extending/README.md, docs/docs/extending/custom-functions.md, docs/docs/extending/importers.md, docs/docs/extending/logger.md, docs/docs/extending/preset-variables.md, docs/docs/extending/values.md, docs/docs/index.md, docs/index.md
The documentation is now updated to cover the new APIs of the library.
Documentation about extension points of the library has been extracted in a new section of the documentation and its content has been completed to explain extension points better.
Links between pages have been replaced with relative links to the markdown files (which are converted by the jekyll plugin), allowing links to work fine when reading the markdown files on github directly rather than using the website.
Closes #369
=> Rewrite the documentation

phpstan-baseline.neon, src/Compiler.php
Colors are expected to support only integers for the R, G and B channels. But some operations were producing floats. Due to becoming stricter on integer validation in other parts of the compiler, this bug became visible.
Closes #397
=> Fix the operations on colors

phpstan-baseline.neon, src/Compiler.php, src/Parser.php
Some wrong phpdoc was omitting the possibility for the source name to be null when a path is not provided, which led to missing it in a few places. With PHP 8.1 deprecating passing null to a bunch of core functions, this was detected.
=> Fix the handling of non-provided paths

composer.json, src/Compiler.php, tests/FrameworkTest.php, tests/specs/sass-spec-exclude.txt
Closes #403 
This reverts #380. fixing spec compliance for lists to avoid breaking list functions is too much work, as it looks like it requires fixing interpolation first.
As Bootstrap seems to compile fine without the `nth` refactoring (even though some other list-related code might have bugs that we already had in 1.4 due to not being spec compliant), I prefer delaying the spec compliance fix to a 2.x release rewriting the parser.
=> Fix bootstrap compilation

phpstan-baseline.neon, src/Base/Range.php, src/CompilationResult.php, src/Compiler.php, src/Compiler/CachedResult.php, src/Formatter.php, src/Formatter/Compressed.php, src/Formatter/Expanded.php, src/Logger/LoggerInterface.php, src/Logger/QuietLogger.php, src/Logger/StreamLogger.php, src/Parser.php, src/SourceMap/SourceMapGenerator.php, src/Util.php, src/Util/Path.php, src/ValueConverter.php, src/Warn.php
This adds native type definitions in most methods thanks to unlocking support for return types and scalar types due to the new min PHP version.
=> Add types for methods

phpstan-baseline.neon, src/Compiler.php
Instead of using the same property to hold the configured formatter class name and the actual formatter instance, the output style is now stored in a dedicated property. This improves type checking.
=> Clean the handling of the output style configuration

src/Compiler.php
In #410, I kept the message `is deprecated` when turning the deprecation into an error.
=> Fix the error message when passing unsupported variables

src/Compiler.php
dart-sass does not implement extending a compound selector, because the way the spec explains the intent of `@extends` would mean that `@extends .foo.bar` should be the same than `@extends .foo, .bar`.
libsass implements its own behavior when extending a compound selector, which is not compatible with the intent of the `@extends` spec, and reports a deprecation warning.
scssphp implements something similar to libsass, without actually being the same (partially caused by the fact that our whole `@extends` implementation is not spec compliant).
This implements the same deprecation warning than libsass, suggesting to use `@extends .foo, .bar` instead of the compound selector `.foo.bar`. In practice, if the expected output was the old libsass one rather than the one corresponding to the …
=> Add a warning when extending a compound selector

.gitattributes, composer.json
The CLI is still there in the repository as a maintenance tool allowing to run the compiler to test it. However, the intended usage of the package is to use the compiler programmatically. Projects able to rely on a CLI tool to compile their Scss files should rather use the official Sass CLI instead.
Closes #417
=> Remove the pscss CLI from the package

phpstan-baseline.neon, vendor-bin/phpstan/composer.json
phpstan removed one of the reported issues between 0.12.88 and 0.12.90.
=> Update the phpstan baseline

docs/docs/README.md
This option is only used when using the legacy API (as it was writing the file to disk). But the doc is showing the modern API so the option has no effect other than introducing confusion.
=> Remove outdated sourcemap option

.github/workflows/ci.yml, phpstan-baseline.neon, vendor-bin/phpstan/composer.json
PHPUnit has added a runtime check for the necessary extensions. As it needs the mbstring extension for some features (that we don't use), we need to use an older version that relied only on the composer requirement.
=> Fix the CI job running without mbstring

src/Node/Number.php
I can't update the GitHub Actions Workflow to include PHP 8.1, because one of phpunit's dependencies is not yet officially compatible with PHP 8.1. However I've hacked around this in a test branch in our repository: https://github.com/WoltLab/scssphp/pull/1. PHP 7.2 is broken there due to this hack, but should work for the actions in this official PR.
-----------------
> Return type of ScssPhp\ScssPhp\Node\Number::offsetExists($offset) should
> either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or
> the #[ReturnTypeWillChange] attribute should be used to temporarily suppress
> the notice
Adding the proper return types does not work, because PHP 7.x does not yet
support the `mixed` type that is needed for offsetGet().
=> Make Node\Number compatible with PHP 8.1

vendor-bin/phpstan/composer.json
The 1.x codebase relies heavily on the baseline to ignore existing issues. But the baseline is sensitive to phpstan version changes, as new versions tend to improve the accuracy of error messages and so change
them.
=> Pin the phpstan version for the 1.x branch

src/Compiler.php, tests/ApiTest.php, tests/outputs/directives.css
- Fix the handling of `@charset` in source files, ignoring it properly
- Implement the `charset` option that was added in dart-sass recently to allow disabling the rendering of the `@charset "UTF-8";` prefix
- ~~Use an UTF-8 BOM as the prefix in compressed mode as it is shorter (this is what dart-sass does).~~ (not applied in 1.x)
=> Improve the handling of charset rules

src/Parser.php
If comments are discarded rather than being added in the CSS output, unterminated interpolations are not an issue, as they are not interpolated.
=> Remove wrong deprecation warnings about unterminated interpolation

src/Compiler.php
The pretty path should still use the windows separator rather than the normalized one.
=> Fix the pretty file path on Windows

tests/compare-scss.sh
This applies the same normalization rules than in our SassSpecTest, making the script more lenient regarding the formatting rules.
=> Improve the comparison script to normalize formatting

src/Compiler.php, tests/specs/sass-spec-exclude.txt
This does the same kind of fix than for #462 but for other color functions that were badly mixing percentages and unitless numbers.
=> Fix the implementation of color-adjusting functions

src/Compiler.php
This is consistent with the behavior of dart-sass. It produces an equivalent CSS (the CSS spec mentions that the UTF-8 BOM must be supported as a way to detect the UTF-8 charset) while being shorter. The charset rule is kept in expanded output as it is human-readable.
=> Use the UTF-8 BOM as prefix in compressed output

src/Compiler.php, tests/ApiTest.php
Due to the internal implementation of the function discovery for core functions, extra names were available for all functions with different positions of dashes/underscores in the function name (additional ones or omitted ones) or a different case. Those functions names are not standard and would be treated as CSS functions by official Sass implementations.
closes #477
=> Add a deprecation warning when calling core functions with wrong names

tests/FrameworkTest.php
foundation actually contains asset files generating CSS, so we don't need to make our own custom entrypoint.
=> Simplify the foundation test

composer.json, tests/FrameworkTest.php
This framework is also tested by the new CI jobs of dart-sass, alongside Foundation, Bootstrap 4 and Bootstrap 5 (that we already test) and Bulma (which uses the indented syntax and so not supported by scssphp).
As bourbon is a Sass framework providing mixins and functions rather than a CSS framework, we test it by compiling their test fixtures (as done by dart-sass).
=> Add tests against the Bourbon framework

bin/pscss
This is the way this option works in official sass implementation, rather than our approach relying on PATH_SEPARATOR. Making the CLI consistent is useful for using it as a drop-in replacement for testing purposes.
=> Allow passing the load-path option multiple times

src/Compiler.php, tests/ApiTest.php
The 2.0 version won't trigger an error for such function names. They will render them as CSS function. The new message makes it clear.
=> Improve the deprecation message for non-standard function names

tests/compare-scss.sh
The sass executable being used is now configurable through the `SASS_EXECUTABLE` environment variable, allowing to use `sassc` instead of `sass` for instance.
The options used when calling the executable are also restricted to options common to sassc and dart-sass (so no `--no-source-map` option, which was useless anyway as that's the default in dart-sass when writing the CSS to stdout) and the expanded style is configured explicitly (as that's not the default in libsass).
This makes it easier to assert our own expectation against official implementation, as it avoids having to edit the script.
=> Make the comparison script able to use sassc

.github/workflows/ci.yml, src/Node/Number.php
With PHP 8.1 being in RC, we need to support it in our 1.x branch, as 2.0 might not be released before PHP 8.1 becomes stable.
This backports https://github.com/scssphp/scssphp/pull/453 to the 1.x branch.
=> Add support for PHP 8.1

src/Compiler.php, tests/ApiTest.php
Refs #477
This replaces the deprecation by the standard behavior, i.e. not considering those non-standard names as equivalent.
=> Enforce the usage of standard names for core functions

tests/FrameworkTest.php
This allows excluding them easily when running tests. There are several reasons that might justify that:
- they are slow (at least the Foundation one)
- when collecting code coverage, they generate so much data that it uses too much memory and makes the process being killed
=> Add a `frameworks` group on the framework tests

src/Ast/Selector/AttributeOperator.php, src/Ast/Selector/AttributeSelector.php, src/Ast/Selector/ClassSelector.php, src/Ast/Selector/Combinator.php, src/Ast/Selector/ComplexSelector.php, src/Ast/Selector/CompoundSelector.php, src/Ast/Selector/IDSelector.php, src/Ast/Selector/ParentSelector.php, src/Ast/Selector/PlaceholderSelector.php, src/Ast/Selector/PseudoSelector.php, src/Ast/Selector/QualifiedName.php, src/Ast/Selector/Selector.php, src/Ast/Selector/SelectorList.php, src/Ast/Selector/SimpleSelector.php, src/Ast/Selector/TypeSelector.php, src/Ast/Selector/UniversalSelector.php, src/Parser/Parser.php, src/Parser/SelectorParser.php, src/Serializer/SerializeVisitor.php, src/Serializer/Serializer.php, src/Util/Character.php, src/Util/EquatableUtil.php, src/Visitor/SelectorVisitor.php, tests/Parser/SelectorParserTest.php
Note that the selector AST currently misses the `unify()` method that is present in `SelectorList` and `SimpleSelector`. Implementing the selector unification algorithm will be done separately (the algo of SimpleSelector is easy, but SelectorList is much more complex).
=> Implement the selector parser ported from dart-sass

src/Ast/Sass/AtRootQuery.php, src/Parser/AtRootQueryParser.php, tests/Parser/AtRootQueryParserTest.php
Continuing my work porting the various parsers. In Sass, the queries of the `@at-root` rule are parsed after resolving interpolation, and so handled by a secondary parser.
=> Implement the AtRootQueryParser ported from dart-sass

src/Parser/KeyframeSelectorParser.php, tests/Parser/KeyframeSelectorParserTest.php
By writing unit tests for it, I discovered a bug in the dart-sass implementation (already fixed in my PHP code, but not yet upstreamed)
=> Implement the keyframe selector parser ported from dart-sass

src/Ast/Selector/ComplexSelector.php, src/Ast/Selector/CompoundSelector.php, src/Ast/Selector/IDSelector.php, src/Ast/Selector/ParentSelector.php, src/Ast/Selector/PseudoSelector.php, src/Ast/Selector/SelectorList.php, src/Ast/Selector/SimpleSelector.php, src/Ast/Selector/TypeSelector.php, src/Ast/Selector/UniversalSelector.php, src/Extend/ExtendUtil.php, src/Serializer/Serializer.php, src/Util/EquatableUtil.php, src/Util/ListUtil.php, tests/Extend/NestingTest.php, tests/Extend/SuperselectorTest.php, tests/Extend/UnificationTest.php
This implements 3 algorithms ported from dart-sass in the Selector API (not yet used by the Compiler):
- `is-superselector()`
- `selector-unify()` (which depends heavily on the previous one)
- the resolution of parent selectors, which is the basis of `selector-nest()` (`selector-nest()` allows passing an arbitrary amount of selectors, which is just a matter of calling that resolution in a loop)
As this logic is not yet used by the compiler, I extracted test cases for them from sass-spec, to allow testing my implementation (and finding cases where I made mistakes in the process of porting the code...)
=> Implement selector manipulation algorithms ported from dart-sass

composer.json
Our setup relies on this plugin intentionally, so we should mark it as allowed when using composer 2.2+.
=> Mark the bamarni/composer-bin-plugin plugin as allowed

tests/SassSpecTest.php
With PHP 8 turning many warnings into Error, some specs that were previously excluded were breaking the script when rebuilding on PHP 8 rather than PHP 7
=> Fix the exclusion list builder to account for Error that can happen

src/Compiler.php, tests/ApiTest.php
=> Fix the generation of sourcemaps without input path

src/Compiler.php, tests/outputs/builtins.css, tests/outputs/comments.css, tests/outputs/directives.css, tests/outputs/extends.css, tests/outputs/functions.css, tests/outputs/import.css, tests/outputs/map.css, tests/outputs/scss_css.css, tests/outputs/selector_functions.css, tests/outputs/selectors.css
This matches the behavior of dart-sass and libsass.
With this change, `DISALLOW_QUOTE_DIFFERENCE=1 phpunit tests/SassSpecTest.php` reports only 3 failures. 2 of them are related to single quotes in CSS imports and the third one to single quotes in an unknown directive. Those are cases where official Sass implementation are not parsing the CSS strings as Sass strings (and so does not manage quotes that are rendered), while we do. This is not an issue, as it is still equivalent CSS.
=> Use double quotes to render strings by default

tests/inputs/color_operators.scss, tests/inputs/comment_incomplete_interpolation.scss, tests/inputs/comments.scss, tests/inputs/operators.scss, tests/outputs/color_operators.css, tests/outputs/comment_incomplete_interpolation.css, tests/outputs/comments.css, tests/outputs/operators.css
Our input tests are including a few behaviors that are considered errors in dart-sass (color arithmetic and broken interpolation in loud comments). Those behavior are deprecated in scssphp but still supported for BC.
Extracting those into dedicated inputs for the testsuite allows comparing the other parts of those tests to the official implementation.
=> Split invalid SCSS inputs into their own input tests

src/Node/Number.php
07:40:37 INFO      [php] User Deprecated: Method "ArrayAccess::offsetSet()" might add "void" as a native return type declaration in the future. Do the same in implementation "ScssPhp\ScssPhp\Node\Number" now to avoid errors or add an explicit @return annotation to suppress this message.
=> Add explicit return type to avoid Symfony debug warning

phpstan-baseline.neon, src/Block.php, src/Compiler/Environment.php
PHP 8.2 deprecates using dynamic properties in classes that are not annotated to allow them explicitly.
The Environment and Block classes were relying on a bunch of undefined properties. This declares them all.
=> Declare all properties used in Environment and Block

phpstan-baseline.neon, src/Block.php, src/Block/AtRootBlock.php, src/Block/CallableBlock.php, src/Block/ContentBlock.php, src/Block/DirectiveBlock.php, src/Block/EachBlock.php, src/Block/ElseBlock.php, src/Block/ElseifBlock.php, src/Block/ForBlock.php, src/Block/IfBlock.php, src/Block/MediaBlock.php, src/Block/NestedPropertyBlock.php, src/Block/WhileBlock.php, src/Compiler.php, src/Parser.php
This makes it easier to analyse the code relying on those properties.
Follow up of #532, moving all new properties of the Block class to child classes needing them.
=> Rework special blocks to use child classes instead of nullable fields

src/Compiler.php, tests/inputs/selector_functions.scss, tests/outputs/selector_functions.css
When processing selector lists, the output of scssphp was semantically equivalent to the output of dart-sass but in a different order. Producing the same output makes it easier to compare the output.
With that change, the `tests/compare-scss.sh` script reports a `PASS` status for `tests/inputs/selector_functions.scss` when comparing to dart-sass.
=> Rework selector-append to match the dart-sass output

tests/compare-scss.sh
The script now allows passing a `INPUT_GLOB` env variable when running it to change the glob matching scss filenames inside the inputs folder. When omitted, it defaults to `*` to compare all files.
This is especially meant to be used in combination with the argument (passing a diff tool) allowing to see the diff between the outputs, to focus the diff on the file being worked on.
=> Allow filtering in the comparison script

src/Type.php
Value types are expected to be used by custom functions. However, types used only to represent the AST are not meant to be used from third-party code.
=> Mark AST-only types as being internal constants

src/Formatter/Compressed.php, tests/CompressedTest.php
Those are a subset of the tests covering the compressed output of dart-sass, as our compressed mode is not compressed as much as dart-sass (the rendering of values or selectors is not managed by the formatter and so does not get compressed).
This also preserves the `!` in preserved comments (i.e. comments starting with `/*!`) in the compressed style. This matches the behavior of dart-sass (which is useless to keep this comment as preserved if another tool is running on the generated CSS).
=> Add tests covering the compressed formatter

phpstan-baseline.neon, src/Parser.php
The parser was keeping the first charset rule found to prepend it in the AST. But the compiler is a no-op for such AST node anyway.
=> Remove dead logic related to parsing charset rules

src/Compiler.php, tests/specs/sass-spec-exclude.txt
The upgrade of sass-spec in #550 brought an improved set of tests for `str-index` (added because dart-sass also contained bugs for some negative index). One of those new tests detected a bug in our implementation (which looks similar to the dart-sass bug btw)
=> Fix the handling of negative numbers in str-insert

src/Formatter.php
This makes the debugging of errors a lot easier, as it avoid leaking the content of the buffer to the output.
=> Properly clean the output buffer when an error occurs during formatting

.github/workflows/ci.yml
This is a much better configuration for the CI than using the production ini file.
=> Use the development ini file in the CI setup

phpstan-baseline.neon, src/Ast/Sass/Statement/MixinRule.php
PHP static analyzers don't support properly the pattern of late initialization right now.
The new code defines the property as nullable and not read-only, to allow changing the property later in case it is null. This is less explicit about the intent of the property, but it is supported by the tooling.
=> Rework the late initialization of the MixinRule::$content property

src/Ast/Css/CssComment.php, src/Ast/Css/CssStyleRule.php, src/Ast/Css/CssValue.php, src/Ast/Css/ModifiableCssStylesheet.php, src/Ast/Css/ModifiableCssValue.php, src/Ast/Sass/AtRootQuery.php, src/Ast/Sass/Expression/BinaryOperationExpression.php, src/Ast/Sass/Expression/CalculationExpression.php, src/Ast/Sass/Expression/UnaryOperationExpression.php, src/Ast/Sass/Import/StaticImport.php, src/Ast/Sass/Statement/HasContentVisitor.php, src/Ast/Selector/AttributeOperator.php, src/Ast/Selector/ComplexSelector.php, src/Ast/Selector/QualifiedName.php, src/Ast/Selector/Selector.php, src/Formatter/OutputBlock.php, src/Logger/QuietLogger.php, src/Logger/StreamLogger.php, src/Parser/KeyframeSelectorParser.php, src/Parser/MediaQueryParser.php, src/Serializer/SerializeResult.php, src/Serializer/SerializeVisitor.php, src/Serializer/SimpleStringBuffer.php, src/Util/ErrorUtil.php, src/Util/NumberUtil.php, src/Util/SpanUtil.php
Most of the new classes are using final classes and/or `@internal` properly to define what will be covered by BC once 2.0 is released, but a few things were missing.
=> Clean the locking of the API for the new 2.0 codebase

src/Ast/Sass/Statement/HasContentVisitor.php, src/Visitor/StatementSearchVisitor.php
This support has been removed in dart-sass as it was not necessary.
=> Remove support for expressions in StatementSearchVisitor

src/Compiler.php
Found this while preparing local project for PHP 8.2
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in ./src/Compiler.php on line 3401
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in ./src/Compiler.php on line 3401
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in ./src/Compiler.php on line 3401
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in ./src/Compiler.php on line 3403
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in ./src/Compiler.php on line 3403
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in ./src/Compiler.php on line 3405
=> fix: php8.2 var in string deprecation

.github/workflows/ci.yml, Makefile, composer.json
This does not link binaries to the root location anymore (no change when using the Makefile as it abstracts it).
`forward-command` is left disabled as we don't want to run it on non-phpstan jobs.
=> Use new recommended config for bamarni-bin

src/Compiler.php, tests/ExceptionTest.php
In PHP 8.1 implicit conversions from floats to integers trigger a deprecation warning.
The change from `assertNumber()` to `assertInteger()` falls in line with the behavior of Dart Sass, which throws an exception if the index isn't a number, if that number isn't an integer, or if that integer isn't a valid index for the given list.
See [list.dart](https://github.com/sass/dart-sass/blob/bc8df44f6a681223d450abdd89013a61bfe90e9f/lib/src/functions/list.dart#L32) and [value.dart](https://github.com/sass/dart-sass/blob/bc8df44f6a681223d450abdd89013a61bfe90e9f/lib/src/value.dart#L118-L120).
I’ve also added two simple test cases.
Current behavior:
-----------------------
Test files:
```scss
.test {
$list: 1, 2, 3;
value: nth($list, 1.5);
}
```
```scss
.test {
$list: 1, 2, 3;
$new-list: …
```
=> Assert that `$n` is an integer for `nth($list, $n)` and `set-nth($list, $n, $value)`

composer.json, src/Parser/FormatException.php, src/Parser/Parser.php, src/Parser/StylesheetParser.php, src/Util/Path.php, tests/Util/PathTest.php
This introduces the dependency on `league/uri` (as decided in #505).
For now, this is not used a lot yet. But one of my next task is to work on the importer system, which will rely on it a lot.
=> Validate the import URI in the new parser

src/Logger/AdaptingLogger.php, src/Logger/LocationAwareLoggerInterface.php, src/Logger/QuietLogger.php, src/Logger/StreamLogger.php, src/Parser/Parser.php, src/Parser/ScssParser.php, src/Parser/StylesheetParser.php, src/SourceSpan/SourceLocation.php, src/StackTrace/Frame.php, src/StackTrace/Trace.php, src/Util.php
This new interface will give more flexibility to loggers to report locations in a structured way.
Once the rewrite is complete, all internal usages of the logger will work with that interface, letting the logger deal with adding the
location in the message for textual output.
The `AdaptingLogger` provides the compatibility layer to support loggers implemented against the 1.x interface.
=> Add an API for location-aware loggers

src/Parser/StylesheetParser.php
This emits a deprecation warning for `$a -$b` and `$a +$b`, since these look like they could be unary operations but they're actually parsed as binary operations. Either explicitly write `$a - $b` or `$a (-$b)`. See https://sass-lang.com/d/strict-unary for more details.
This deprecation is only implemented for the new parser ported from dart-sass, not for the legacy parser.
See https://github.com/sass/sass/issues/1912 (implemented in dart-sass in https://github.com/sass/dart-sass/pull/1800)
=> Emit a deprecation warning for the strict parsing of unary operators

src/Ast/Sass/Expression/NumberExpression.php, src/Parser/Parser.php, src/Parser/StylesheetParser.php, src/Serializer/SerializeVisitor.php, src/Util/NumberUtil.php, src/Value/ComplexSassNumber.php, src/Value/SassColor.php, src/Value/SassNumber.php, src/Value/SingleUnitSassNumber.php, src/Value/UnitlessSassNumber.php, tests/Value/SassColor/SassColorTest.php, tests/Value/SassNumber/UnitlessIntegerTest.php
This is only applied to the new codebase, not to the old one, as it is scheduled for removal.
see https://github.com/sass/sass/issues/2892 and https://github.com/sass/dart-sass/pull/1802
=> Consistently use floating point numbers

composer.json
The version 6.8 introduces usages of Sass modules, which are not supported yet.
=> Use zurb/foundation 6.7 for the framework tests

src/Parser.php, tests/ExceptionTest.php
This avoids reporting the error as being on line 1 column 0 while we don't know where the file contains an invalid character.
Closes https://github.com/scssphp/scssphp/issues/652
=> Improve the error reporting for invalid UTF-8

src/Compiler.php, tests/inputs/extending_is_selector.scss, tests/outputs/extending_is_selector.css
moved from: https://github.com/scssphp/scssphp/pull/653 to 1.x
collapseSelectors throw Exception if `@extend` is used with a selector that also is combined with `:is()`
eg:
```scss
.item-header {
@extend .specific-item-header;
}
:is(.some-table-header, .specific-item-header ) {
padding: 14px 14px 0;
} 
```
=> fix collapse selector on single node

composer.json, src/Importer/CanonicalizeResult.php, src/Importer/FilesystemImporter.php, src/Importer/ImportCache.php, src/Importer/ImportContext.php, src/Importer/ImportUtil.php, src/Importer/Importer.php, src/Importer/ImporterResult.php, src/Importer/NoOpImporter.php, src/Importer/SpecialCacheValue.php, src/Util/Path.php, src/Util/UriUtil.php, tests/Util/PathTest.php
This implements the importer system ported from dart-sass.
`ImportCache` is the main (internal) entrypoint of that system, turning a requested `UriInterface` into its canonical URL (which identifies uniquely what needs to be loaded) and importing a canonical url as a parsed `Stylesheet` object.
The `Importer` abstract class is the public extension point of that system, allowing to customize the loading of files. The FilesystemImporter is the core implementation that implements the official behavior for filesystem imports.
The FilesystemImporter is intentionally limited to `file:` URLs to match the behavior of dart-sass and keep the same optimizations than dart-sass for `couldCanonicalize`. Support for stream wrappers as discussed in https://github.com/scssphp/scssphp/issues/256 will have …
=> Implement the Importer layer

Makefile
This makes it easier than remembering the command.
`make standard` is also updated to rely on the config file, as done in the CI job.
=> Add Makefile command to fix coding standards

src/Ast/Selector/Selector.php, src/Compiler.php, src/Deprecation.php, src/DeprecationStatus.php, src/Importer/ImportCache.php, src/Logger/AdaptingDeprecationAwareLogger.php, src/Logger/DeprecationAwareLoggerInterface.php, src/Logger/DeprecationHandlingLogger.php, src/Logger/LocationAwareLoggerInterface.php, src/Logger/QuietLogger.php, src/Parser/Parser.php, src/Parser/ScssParser.php, src/Parser/StylesheetParser.php, src/Value/SassCalculation.php, src/Value/Value.php, src/Warn.php
This implements the deprecation handling logic of dart-sass.
The various configuration settings supported by the DeprecationHandlingLogger will be configured in the Compiler class once it is rewritten, exposing new configuration settings.
Note all values of the Deprecation enum have been ported yet. Deprecations that only make sense for an implementation supporting modules are not there yet. However, I added the deprecations that are expected to be implemented in our 2.0 release even though they are not all implemented yet (because they are triggered in code that is not ported yet).
Values that are specific to dart-sass and won't ever be implemented are not ported either:
- `nullAlpha` because our SassColor API already forbids passing `null` entirely as it is new and so we don't have any …
=> Implement the deprecation handling logic

src/Ast/Sass/Expression/IsCalculationSafeVisitor.php, src/Ast/Sass/Statement/IfRuleClause.php, src/Util/IterableUtil.php, src/Util/ListUtil.php, src/Visitor/AnySelectorVisitor.php, src/Visitor/EveryCssVisitor.php, src/Visitor/SelectorSearchVisitor.php, src/Visitor/StatementSearchVisitor.php
The `every` and `any` method work for any iterable, not just for lists. And `search` was already typed using `iterable`.
This will let me reuse them in more places in future PRs porting code.
=> Separate list utilities from iterable utilities

phpstan-baseline.neon, phpstan-no-baseline.neon, src/Ast/Selector/SelectorList.php, src/Block/CallableBlock.php, src/Compiler.php, src/Node/Number.php, src/Parser/StylesheetParser.php, src/SourceSpan/SourceFile.php, src/Util/ListUtil.php, src/Value/SassCalculation.php, src/Value/SingleUnitSassNumber.php
As the new code works a lot with the list type, we should make phpstan enforce it, which is the case only in bleeding edge for now. As phpstan is pinned to an exact version, the fact that bleeding edge can enable new rules in any release (and so change the result of the analysis) is not an issue.
=> Enable bleeding edge rules for phpstan

composer.json
The output of this var-dumper is much more readable than var_dump when debugging the logic.
=> Add symfony/var-dumper as a dev dependency

src/OutputStyle.php
Those methods converting from and to a string will still be available in 2.0 once the constants are replaced with an enum.
=> Add helper methods to OutputStyle to help supporting 2.0.

src/Extend/ConcreteExtensionStore.php
When porting the extension store from dart-sass, phpstan detected an issue about the way an extender was removed from a map using selectors as keys. In #682, I wrote the code by removing the selector of that extender instead. However, the decision taken in https://github.com/sass/dart-sass/pull/2129 ended up being the alternative choice of removing the no-op deletion. This synchronizes the code with that decision.
=> Update the extension store to match the decision taken in dart-sass

src/Parser.php, tests/ApiTest.php
When parsing only a value, the parser runs without an env being set. Inside values, comments are always discarded. So moving our assertion inside the condition that actually needs it is enough and fixes the issue.
Closes #689
=> Fix the usage of comments when parsing values

src/Parser.php, tests/ApiTest.php
The logic was not ensuring that all the input has been consumed by the parsing, ignoring silently the remaining content. This behavior is now deprecated, ensuring only a valid value is passed.
While looking at https://github.com/scssphp/scssphp/issues/689, I figured out that our value parsing silently ignores extra content that  comes after the expression instead of enforcing that the value corresponds to the whole input. This triggers a deprecation warning in that case, allowing to turn that into an error in 2.0 (where the new way to parse values won't allow extra content anyway)
=> Deprecate passing trailing data in value parsing

src/Parser.php, tests/ApiTest.php
This turns the deprecation of #691 into an actual error for 2.0
=> Forbid trailing content when parsing values

src/Node/Number.php
Variables gets encoded as JSON as part of the cache key. For most types, this is fine as they are represented as arrays. But numbers are represented as an object with private properties so all numbers were encoded the same, breaking the cache invalidation when replacing them with a different number.
Closes #699
=> Fix the compilation cache key when using numbers in variables

phpstan-baseline.neon, src/Collection/Map.php, src/Evaluation/EvaluationContext.php, src/Function/ColorFunctions.php, src/Function/FunctionRegistry.php, src/Function/ListFunctions.php, src/Function/MapFunctions.php, src/Function/MathFunctions.php, src/Function/MetaFunctions.php, src/Function/SelectorFunctions.php, src/Function/StringFunctions.php, src/Util/ArrayUtil.php, src/Util/Character.php, src/Util/NumberUtil.php, src/Util/StringUtil.php, src/Warn.php
This implements all the global functions of the core (functions that are only exposed from built-in modules have not been ported from dart-sass yet as modules are not implemented for now), except for the special functions of `sass:meta` that require being implemented in the evaluator itself because they access its internals (those are implemented in #709).
Each sass module is implemented as a separate internal class with static methods for each callable (one per function generally, but overloaded functions will have several associated callables).
The `FunctionRegistry` is our registry of core functions, allowing us to lazy-load the `BuiltInCallable` only when a function is used for the first time (for now, the  `FunctionRegistry` does not perform any caching of those SassCallable objects …
=> Implement global functions for the new evaluation system

composer.json
Mixing a dev stability for `league/uri` while forcing stable versions for `league/uri-interfaces` does not work well because `league/uri` does not properly define the min version it requires (at least in its dev version)
=> Fix the version of league/uri used in CI

src/Evaluation/ArgumentResults.php, src/Evaluation/Environment.php, src/Evaluation/EvaluateResult.php, src/Evaluation/EvaluateVisitor.php, src/Evaluation/LoadedStylesheet.php, src/Evaluation/VisitorEvaluationContext.php, src/SassCallable/UserDefinedCallable.php, src/Util/AstUtil.php, src/Util/IterableUtil.php, src/Util/MakeExpressionCalculationSafe.php, src/Util/StringUtil.php, src/Visitor/ReplaceExpressionVisitor.php
This implements the evaluation for ported from dart-sass. However, it does not wire it in our Compiler class yet (this will be done in a separate PR).
The code has a bunch of TODOs related to exceptions. The structure of our new exceptions will be updated in another PR to better reflect the dart-sass exceptions while keeping our constraints into account (in Dart, any class can be _implemented_ as an interface, and their exceptions rely on that, while we will have to separate the interface and the "default" implementation of it)
=> Implement the evaluation based on the new AST

src/Ast/Sass/Expression/StringExpression.php, src/Compiler.php, src/Exception/SassFormatException.php, src/Exception/SassRuntimeException.php, src/Formatter.php, src/Logger/AdaptingDeprecationAwareLogger.php, src/Logger/AdaptingLogger.php, src/Logger/QuietLogger.php, src/Node/Number.php, src/Parser.php, src/Value/ComplexSassNumber.php, src/Value/SassColor.php, src/Value/SassNumber.php, src/Value/SingleUnitSassNumber.php, src/Value/UnitlessSassNumber.php, src/Warn.php
Implicit nullable types will be deprecated in PHP 8.4.
This is not applied on the 1.x branch because explicit nullable types are not compatible with PHP 5.6.
The diff of this PR is entirely automated using `php-cs-fixer.phar fix --rules=nullable_type_declaration_for_default_null_value src`
=> Use explicit nullable types

tests/ApiTest.php
Top-level declarations are not valid in Sass.
=> Use valid Sass files in ApiTest

docs/docs/extending/custom-functions.md, src/Compiler.php, tests/ApiTest.php
Supporting this second argument in the 2.x codebase will be a pain for the BC layer. It is easier to drop support for it.
The only usages of this argument in core are for cases of overloaded functions where it allows us to distinguish which signature was selected. However, there is no such case for custom function as they don't support overloads. All valid cases can be implemented using only the first argument (and this is what the documentation shows).
=> Deprecate the second argument passed to custom functions

src/Compiler.php, src/Type.php
Some internal types or pseudo-constants on the Compiler were missing the `@internal` flag.
=> Add proper tags on some internal APIs

composer.json, src/Util.php
The polyfill is already a transitive dependency because of `symfony/filesystem`. And all the code of the new API is already implemented by using mbstring directly (assuming it is either available or polyfilled).
The ponyfill utilities used in the 1.x codebase have been simplified internally but not replaced as the code using them will be deleted soon so it was not worth it.
Related to #302
=> Add an explicit dependency on the mbstring polyfill

src/Evaluation/EvaluateVisitor.php, src/Parser/Parser.php, src/Serializer/SerializeVisitor.php, src/Serializer/Serializer.php, src/Util/ParserUtil.php, src/Value/SassNumber.php, src/Value/SassString.php
The issue with the escape sequence detection was at least partially hidden by the usage of ponyfills because `Util::mbChr` has a return type `string` while `mb_chr` returns `string|false` (which for some reason is not reported by phpstan either)
=> Fix more mistakes in ported code

Makefile
The verbose mode allows to see error identifiers, which is helpful when wanting to ignore them.
=> Add a make recipe to run phpstan in verbose mode

phpcs.xml.dist, src/SourceSpan/Highlighter/AsciiGlyph.php, src/SourceSpan/Highlighter/Highlight.php, src/SourceSpan/Highlighter/Highlighter.php, src/SourceSpan/Highlighter/Line.php, src/SourceSpan/SourceSpanMixin.php, src/SourceSpan/Util.php, tests/SourceSpan/HighlighterTest.php, tests/SourceSpan/MultipleHighlightTest.php, tests/SourceSpan/SimpleSourceSpanTest.php
This implements the source span highlighting by porting it from https://github.com/dart-lang/source_span/
Differences:
- my implementation does not support coloring the output with ANSI terminal color escape sequences. We don't need it in scssphp (as our focus is not on providing a CLI tool) and it makes things easier.
- my implementation does not support using an Unicode output instead of the ASCII output (for nicer lines in the multi-line highlights mostly). **All** unit tests of the source_span package and **all** specs in sass-spec are written against the ASCII format. And Dart relies on a global state to switch between both sets of glyphs. Implementing only the ASCII output makes the code simpler and avoids the need for this global state
=> Implement the source span highlighting

src/SourceSpan/ConcreteFileSpan.php, src/SourceSpan/Highlighter/Highlighter.php, src/SourceSpan/LazyFileSpan.php, src/SourceSpan/SimpleSourceSpan.php, src/SourceSpan/SimpleSourceSpanWithContext.php, src/SourceSpan/SourceFile.php, src/SourceSpan/SourceSpanMixin.php, src/SourceSpan/Util.php
This copies the few utilities used in that namespace in its dedicated `Util` class to make it independent from the rest of the repository.
This prepares extracting the source_span port in a dedicated package.
As I have ported the full source_span package now (since #742), I'm fine with providing BC on the ported code. And I have a use case when this SourceSpan package would allow me to provide better error messages so I might reuse it.
=> Make the SourceSpan namespace standalone

src/Util/Path.php, tests/Util/PathTest.php
This was a mistake while porting the dart code because `scandir()` returns relative paths, not absolute paths.
=> Fix path canonicalization for case-insensitive filesystems

src/Evaluation/EvaluateVisitor.php, src/Function/FunctionRegistry.php, src/Parser/CssParser.php
When implementing the parser initially, the FunctionRegistry was not implemented yet so I reused the API of the old compiler to identify Sass functions. This refactors that code to be ready for the removal of the old compiler.
=> Refactor the CssParser to use the FunctionRegistry for known functions

bin/pscss
- Ensure that the CSS is written with a final EOL
- Use `Compiler::compileFile` when using a file as input
- Rename the variable holding the compiler to make the code clearer
=> Refactor the CLI tool

tests/SourceSpan/MultipleHighlightTest.php
This test has also been submitted upstream at https://github.com/dart-lang/source_span/pull/116
=> Add a test covering the highlighting of non-contiguous spans

src/Ast/Css/CssDeclaration.php, src/Ast/Css/CssNode.php, src/Ast/Css/ModifiableCssDeclaration.php, src/Ast/Sass/Expression/StringExpression.php, src/Ast/Selector/SelectorList.php, src/Compiler.php, src/Deprecation.php, src/Evaluation/EvaluateVisitor.php, src/Function/MetaFunctions.php, src/Parser/SassParser.php, src/Parser/StylesheetParser.php, src/Serializer/SerializeVisitor.php, src/Serializer/Serializer.php, tests/SassSpecTest.php
A few changes have been excluded from this update:
- the implementation of the `global-builtin` future deprecation, as that deprecation only makes sense when Sass modules are supported (for the same reason, we don't implement yet the `import` future deprecation)
- the implementation of the new Color API for color spaces (as it relies on modules to be usable)
=> Sync ported code from dart-sass

phpstan-baseline.neon, src/Util/NumberUtil.php, vendor-bin/phpstan/composer.json
PHP 8.4 has deprecated the usage of the exponentiation operator with 0 as base and a negative exponent, to be consistent with the behavior of `pow` for integers. It also introduces a new `fpow` function to expose the standard behavior for floats (which we want to keep, as Sass numbers are floats).
=> Fix exponentation deprecation for PHP 8.4

bin/pscss, src/Compiler.php
This makes the signature of the method compatible with the equivalent API in dart-sass.
Passing an importer allows to handle the case where the source being compiled corresponds to a canonical URL handled by an importer that is not a filesystem importer.
=> Update the signature of `compileString` to allow passing an importer

tests/ApiTest.php
This adds a test covering the fix done in #787 to prevent future regressions.
=> Add a test covering the generation of inline source maps

src/Ast/Sass/Interpolation.php
dart-sass performs some checks for the types of elements in an Interpolation because Dart does not support union types (and so this is not checked by the compiler).
This check is redundant in our case because we use a union type for the precise type, and phpstan detects this as dead code due to the condition always being false.
I kept a comment here to simplify updates with dart-sass changes.
=> Remove check redundant with static analysis
