scssphp/scssphp

src/Compiler.php
tests/inputs/looping.scss
tests/outputs/looping.css
tests/outputs_numbered/looping.css

I don't get the test to run so I can't add a unit tests at this point. Fix works as intended. See issue #29

Fix: @each is forcing unwanted type conversion #29

---

src/Compiler.php

Due to the multiple prototypes being tried in chain, native functions are throwing errors even in valid code, which will be swallowed when finding a compatible prototype. In case of failure, the catched exception message is sent back to the `throwError` API. This has 2 effects:
- due to the double usage of `throwError`, the details about the location and call trace get duplicated in the final message
- computing the call trace message is very costly due to the size of the call trace. Computing it for exceptions which will be swallowed is a useless performance hit.
Places catching exceptions are now toggling a flag which tells `throwError` to skip adding the details. This avoids both the performance hit of multiple prototypes and the duplicated details (as the first call to `throwError` is …

Fix the handling of call traces for exceptions of native functions

---

.gitattributes

Remove box.json.dist from .gitattributes

---

bin/pscss
src/Compiler.php

Remove ignore errors

---

src/Compiler.php
tests/specs/sass-spec-exclude.txt

This avoids accessing an array offset on null

Add error handling for invalid type in some color functions

---

tests/SassSpecTest.php

This has several benefits:
- it makes it possible to run tests on Windows (I haven't tried it yet to see whether they are passing or no, but the usage of `passthru` with a Unix command made that entirely impossible before)
- it goes a bit faster (the testsuite run takes a few seconds less, thanks to avoiding the overhead of spawning a child process)
As an additional benefit, I refactored the cleaning to be performed in a phpunit teardown method (using `@after` rather than overriding `tearDown` to avoid issues with the signature change in PHPUnit 8). this ensures that the cleaning also happens when an exception is raised, either because of a failure or because of expecting an exception (the cleaning on line 326 was never reached for passing tests)

Use PHP methods to do IO rather than a shell command

---

src/Parser.php

Fix compat with PHP 5.6

---

src/Parser.php

Same than the refactoring done in #156 but for the Parser

Migrate from throwParseError to a parseError factory in the Parser

---

composer.json

Hi,
I took the liberty to open this small pull request which should add support for php 8 - thanks for your efforts! :)
- fixed assuming property as array when being null
- upgraded phpunit requirement for php 8

PHP 8 support

---

src/Compiler.php
src/Parser.php
src/Type.php
tests/inputs/looping.scss
tests/inputs/operators.scss
tests/outputs/looping.css
tests/outputs/operators.css

This is basically a revert of https://github.com/leafo/scssphp/pull/374 which added non-compliant experimental features.
Closes #187

Remove experimental features

---

scss.inc.php
tests/IncFileTest.php

This also adds a unit test ensuring that this file loads all files of the source code to avoid such issue in the future.

Fix the loading of SassScriptException in scss.inc.php

---

docs/docs/index.md
docs/index.md

Changes done in 1.3 are not reflected one the website yet. And there were a few other content issues.

Update the doc for the website

---

src/Compiler.php
tests/ExceptionTest.php

Deprecate color arithmetic

---

tests/SassSpecTest.php

This ensures a better isolation of tests between each other.

Use separate compiler instance for each spec test

---

bin/pscss
docs/docs/index.md
src/Compiler.php
tests/SassSpecTest.php

Refactor the resolution of imports to be spec compliant 

---

.github/workflows/ci.yml
src/Compiler.php

Closes #230
The CI will now ensure this keeps working.

Fix usage with iconv but not mbstring

---

src/Cache.php
src/Version.php

https://github.com/scssphp/scssphp/issues/268#issuecomment-724783383
+ update the lib version that was unsynchronised since the last release

Append the lib version as a cache invalider 

---

src/Parser.php
tests/specs/sass-spec-exclude.txt

treat css custom properties as valid css element

---

src/Compiler.php

This bug was caused by concurrent refactorings.

Fix the usage of the logger in new color functions

---

src/Colors.php
src/Compiler.php
src/Compiler/CompilationResult.php
src/Logger/LoggerInterface.php

These comes from reports by phpstan in my experiment to use it.

Improve some phpdoc

---

docs/_config.yml
docs/index.md

This was forgotten when doing the last releases

Fix the current version on the website

---

tests/FrameworkTest.php

- properly compile the Foundation styles instead of only parsing the definition of mixins, to ensure better compat
- don't catch exceptions before asserting they are null. Letting PHPUnit catch the exception allows a much better reporting in case of failure.

Rework the Framework tests

---

src/Compiler.php

This is better than hardcoding a special case for it in the function invocation logic.

Move the handling of the 2-args signature for hsl to the function

---

src/Compiler.php

This uses the same overloaded signature than dart-sass to implement it. See the discussion on https://github.com/sass/libsass/issues/2927
This removes a hack in the argument validation that was used to make the spec pass (and it unlocks my other work on refactoring the handling of arguments, as this hack was blocking me as I could not reproduce it easily).

Refactor the implementation of map-remove

---

bin/pscss

Deprecate --dump-tree in the CLI

---

MAINTENANCE.md
Makefile
composer.json

As part of updating sass-spec, I took the opportunity to document the process (and to streamline it a bit)

Update sass-spec and document this process

---

src/Compiler.php
src/Parser.php

Deprecate the scssphp-import-once directive

---

phpstan-baseline.neon
vendor-bin/phpstan/composer.json

This does not change the content of the baseline. But the new version of phpstan changes the order of the baseline to make the sorting more stable when code is moved in the file.

Regenerate the phpstan baseline

---

src/Compiler.php
tests/inputs/counter.scss
tests/outputs/counter.css

This also adds a test covering it.

Declare arguments for the counter function

---

phpstan-baseline.neon
src/Base/Range.php
src/Block.php
src/Cache.php
src/Colors.php
src/Compiler.php
src/Compiler/Environment.php
src/Exception/CompilerException.php
src/Exception/ParserException.php
src/Exception/RangeException.php
src/Formatter.php
src/Formatter/Compact.php
src/Formatter/Compressed.php
src/Formatter/Crunched.php
src/Formatter/Debug.php
src/Formatter/Expanded.php
src/Formatter/Nested.php
src/Formatter/OutputBlock.php
src/Logger/StreamLogger.php
src/Node.php
src/Parser.php
src/SourceMap/Base64.php
src/SourceMap/Base64VLQ.php
src/SourceMap/SourceMapGenerator.php
src/Util.php

Tag internal APIs as being internal and the Compiler as wanna-be final

---

src/Exception/ServerException.php

Mark the ServerException as deprecated.

---

composer.json
tests/ExceptionTest.php
tests/specs/sass-spec-exclude.txt

In the time between opening #387 and merging it, my remaining PR on sass-spec got merged...

Upgrade sass-spec again

---

.github/workflows/ci.yml
bin/pscss
composer.json
scss.inc.php

Drop support for PHP older than 7.2

---

phpstan-baseline.neon
src/Base/Range.php
src/Block.php
src/Cache.php
src/Colors.php
src/CompilationResult.php
src/Compiler.php
src/Compiler/CachedResult.php
src/Compiler/Environment.php
src/Exception/CompilerException.php
src/Exception/ParserException.php
src/Exception/RangeException.php
src/Exception/SassScriptException.php
src/Formatter.php
src/Formatter/Compressed.php
src/Formatter/Expanded.php
src/Node/Number.php
src/Parser.php
src/SourceMap/Base64.php
src/SourceMap/Base64VLQ.php
src/SourceMap/SourceMapGenerator.php
src/Type.php
src/Util.php
src/Util/Path.php
src/Version.php

Restrict access to internal APIs

---

phpstan-baseline.neon
src/Exception/ParserException.php
src/Exception/SassScriptException.php

Add types in exceptions

---

src/Parser.php
tests/inputs/operators.scss
tests/outputs/operators.css

Closes #434 
Closes #435 
TODO:

Fix the parsing of expressions alterning operator precedence

---

phpstan-baseline.neon
vendor-bin/phpstan/composer.json

The new version of phpstan triggers a slightly different error message

Update the phpstan baseline

---

src/Compiler.php
tests/specs/sass-spec-exclude.txt

Refs #459 (this fixes the second issue reported in it)

Fix the handling of CSS variables in rgba()

---

tests/specs/sass-spec-exclude.txt

Update the list of excluded specs

---

docs/docs/changelog.md

Add missing attribution in the changelog

---

src/Parser/StylesheetParser.php

This ports the fix done in [dart-sass 1.42.1](https://github.com/sass/dart-sass/releases/tag/1.42.1)

Fix the parsing of interpolation in calc in the new parser

---

src/Compiler.php
src/Parser.php
tests/FrameworkTest.php

Fix the tracking of comment locations for the sourcemap

---

src/Compiler.php
tests/inputs/at_root_in_nested_mixin.scss
tests/outputs/at_root_in_nested_mixin.css

Fix the handling of nested at-root in nested mixins

---

.github/workflows/ci.yml

This makes the test setup a bit faster.

Use the preinstalled PHP 8.1 version on CI

---

phpstan-baseline.neon
src/Compiler.php
src/Node/Number.php
tests/ExceptionTest.php

Improve error messages for incorrect units in color functions

---

src/Compiler.php
src/Node/Number.php

See https://github.com/sass/sass/issues/1890

Deprecate passing a limit with unit to random()

---

phpstan-no-baseline.neon
src/Extend/ExtendUtil.php
vendor-bin/phpstan/composer.json

The new version caught a bug in my ported code.

Upgrade phpstan to 1.8.3

---

src/Compiler.php
src/Parser/StylesheetParser.php

This matches the update done in dart-sass

Update links in warning messages

---

src/Parser.php
tests/inputs/media_query_interpolation_spaces.scss
tests/outputs/media_query_interpolation_spaces.css

Fixes https://github.com/scssphp/scssphp/issues/622

Fix the handling of leading spaces in interpolated media queries

---

.github/workflows/ci.yml
Makefile
phpcs.xml.dist
src/Compiler.php
src/Node/Number.php
tests/SassSpecTest.php

This is similar to the work done in https://github.com/scssphp/scssphp/pull/675 but applied to the 1.x branch as it is still maintained.

Fix coding standards

---

src/Evaluation/Environment.php
src/Evaluation/EvaluateVisitor.php
src/Evaluation/EvaluationContext.php
src/Extend/ConcreteExtensionStore.php
src/Extend/ExtendUtil.php
src/Extend/ExtensionStore.php
src/Function/MapFunctions.php
src/Function/MathFunctions.php
src/Importer/CanonicalizeContext.php
src/Importer/ImportContext.php
src/Parser/Parser.php
src/Parser/StylesheetParser.php
src/Serializer/SerializeVisitor.php
src/Util/ArrayUtil.php
src/Util/IterableUtil.php
src/Value/SassCalculation.php
src/Value/SassNumber.php

This can help phpstan produce a more precise analysis.

Add annotations for callbacks that are called immediately

---

src/Evaluation/EvaluateVisitor.php

This will allow to keep our feature of custom variables registered in the compiler, even though dart-sass does not have this feature.

Implement support for initial variables in the evaluator

---

src/Compiler.php

Moving the public API (which will be preserved) before the internal implementation (which is removed in #728) will makes it diff more usable by letting git detects that those functions are still there (with small changes) while it cannot if they move too much.

Reorganize compiler methods

---

.github/workflows/ci.yml
composer.json

Bump the min PHP version to PHP 8.2

---

src/Ast/Sass/ArgumentDeclaration.php
src/Ast/Selector/SelectorList.php
src/Ast/Selector/SimpleSelector.php
src/Compiler.php
src/Evaluation/EvaluateVisitor.php
src/Exception/MultiSpanSassException.php
src/Exception/MultiSpanSassFormatException.php
src/Exception/MultiSpanSassRuntimeException.php
src/Exception/MultiSpanSassScriptException.php
src/Exception/SassException.php
src/Exception/SassFormatException.php
src/Exception/SassRuntimeException.php
src/Exception/SassScriptException.php
src/Exception/SimpleSassException.php
src/Exception/SimpleSassFormatException.php
src/Exception/SimpleSassRuntimeException.php
src/Extend/ConcreteExtensionStore.php
src/Extend/Extender.php
src/Extend/MergedExtension.php
src/Logger/DeprecationHandlingLogger.php
src/Parser/FormatException.php
src/Parser/InterpolationMap.php
src/Parser/MultiSourceFormatException.php
src/Parser/Parser.php
src/Serializer/SerializeVisitor.php
src/Util/ErrorUtil.php

This implements the multi-span exceptions allowing to have the full error reporting logic.

Implement the exception hierarchy

---

src/Compiler.php

Fix the rendering of inline source maps
